import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Bacterias",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <div className="app-container">{children}</div>
      </body>
    </html>
  )
}
